/* automatically generated by rust-bindgen */

pub type __uint8_t = crate::libc::c_uchar;
pub type __uint32_t = crate::libc::c_uint;
pub type __uint64_t = crate::libc::c_ulong;
pub type FStar_UInt128_uint128 = [u64; 2];
extern "C" {
    pub fn Hacl_Curve25519_51_fsquare_times(
        o: *mut u64,
        inp: *mut u64,
        tmp: *mut FStar_UInt128_uint128,
        n: u32,
    );
}
extern "C" {
    pub fn Hacl_Curve25519_51_finv(o: *mut u64, i: *mut u64, tmp: *mut FStar_UInt128_uint128);
}
extern "C" {
    pub fn Hacl_Curve25519_51_scalarmult(out: *mut u8, priv_: *mut u8, pub_: *mut u8);
}
extern "C" {
    pub fn Hacl_Curve25519_51_secret_to_public(pub_: *mut u8, priv_: *mut u8);
}
extern "C" {
    pub fn Hacl_Curve25519_51_ecdh(out: *mut u8, priv_: *mut u8, pub_: *mut u8) -> bool;
}
