/* automatically generated by rust-bindgen */

pub type __uint8_t = crate::libc::c_uchar;
pub type __uint32_t = crate::libc::c_uint;
pub type __uint64_t = crate::libc::c_ulong;
pub type FStar_UInt128_uint128 = [u64; 2];
pub type Spec_Hash_Definitions_hash_alg = u8;
extern "C" {
    pub fn Hacl_Hash_Core_Blake2_update_blake2s_32(s: *mut u32, totlen: u64, block: *mut u8)
        -> u64;
}
extern "C" {
    pub fn Hacl_Hash_Core_Blake2_finish_blake2s_32(s: *mut u32, ev: u64, dst: *mut u8);
}
extern "C" {
    pub fn Hacl_Hash_Core_Blake2_update_blake2b_32(
        s: *mut u64,
        totlen: FStar_UInt128_uint128,
        block: *mut u8,
    ) -> FStar_UInt128_uint128;
}
extern "C" {
    pub fn Hacl_Hash_Core_Blake2_finish_blake2b_32(
        s: *mut u64,
        ev: FStar_UInt128_uint128,
        dst: *mut u8,
    );
}
extern "C" {
    pub fn Hacl_Hash_Blake2_update_multi_blake2s_32(
        s: *mut u32,
        ev: u64,
        blocks: *mut u8,
        n_blocks: u32,
    ) -> u64;
}
extern "C" {
    pub fn Hacl_Hash_Blake2_update_multi_blake2b_32(
        s: *mut u64,
        ev: FStar_UInt128_uint128,
        blocks: *mut u8,
        n_blocks: u32,
    ) -> FStar_UInt128_uint128;
}
extern "C" {
    pub fn Hacl_Hash_Blake2_update_last_blake2s_32(
        s: *mut u32,
        ev: u64,
        prev_len: u64,
        input: *mut u8,
        input_len: u32,
    ) -> u64;
}
extern "C" {
    pub fn Hacl_Hash_Blake2_update_last_blake2b_32(
        s: *mut u64,
        ev: FStar_UInt128_uint128,
        prev_len: FStar_UInt128_uint128,
        input: *mut u8,
        input_len: u32,
    ) -> FStar_UInt128_uint128;
}
extern "C" {
    pub fn Hacl_Hash_Blake2_hash_blake2s_32(input: *mut u8, input_len: u32, dst: *mut u8);
}
extern "C" {
    pub fn Hacl_Hash_Blake2_hash_blake2b_32(input: *mut u8, input_len: u32, dst: *mut u8);
}
extern "C" {
    pub fn Hacl_Hash_MD5_legacy_update_multi(s: *mut u32, blocks: *mut u8, n_blocks: u32);
}
extern "C" {
    pub fn Hacl_Hash_MD5_legacy_update_last(
        s: *mut u32,
        prev_len: u64,
        input: *mut u8,
        input_len: u32,
    );
}
extern "C" {
    pub fn Hacl_Hash_MD5_legacy_hash(input: *mut u8, input_len: u32, dst: *mut u8);
}
extern "C" {
    pub fn Hacl_Hash_Core_MD5_legacy_init(s: *mut u32);
}
extern "C" {
    pub fn Hacl_Hash_Core_MD5_legacy_update(abcd: *mut u32, x: *mut u8);
}
extern "C" {
    pub fn Hacl_Hash_Core_MD5_legacy_pad(len: u64, dst: *mut u8);
}
extern "C" {
    pub fn Hacl_Hash_Core_MD5_legacy_finish(s: *mut u32, dst: *mut u8);
}
extern "C" {
    pub fn Hacl_Hash_SHA1_legacy_update_multi(s: *mut u32, blocks: *mut u8, n_blocks: u32);
}
extern "C" {
    pub fn Hacl_Hash_SHA1_legacy_update_last(
        s: *mut u32,
        prev_len: u64,
        input: *mut u8,
        input_len: u32,
    );
}
extern "C" {
    pub fn Hacl_Hash_SHA1_legacy_hash(input: *mut u8, input_len: u32, dst: *mut u8);
}
extern "C" {
    pub fn Hacl_Hash_Core_SHA1_legacy_init(s: *mut u32);
}
extern "C" {
    pub fn Hacl_Hash_Core_SHA1_legacy_update(h: *mut u32, l: *mut u8);
}
extern "C" {
    pub fn Hacl_Hash_Core_SHA1_legacy_pad(len: u64, dst: *mut u8);
}
extern "C" {
    pub fn Hacl_Hash_Core_SHA1_legacy_finish(s: *mut u32, dst: *mut u8);
}
extern "C" {
    pub fn Hacl_Hash_SHA2_update_multi_224(s: *mut u32, blocks: *mut u8, n_blocks: u32);
}
extern "C" {
    pub fn Hacl_Hash_SHA2_update_multi_256(s: *mut u32, blocks: *mut u8, n_blocks: u32);
}
extern "C" {
    pub fn Hacl_Hash_SHA2_update_multi_384(s: *mut u64, blocks: *mut u8, n_blocks: u32);
}
extern "C" {
    pub fn Hacl_Hash_SHA2_update_multi_512(s: *mut u64, blocks: *mut u8, n_blocks: u32);
}
extern "C" {
    pub fn Hacl_Hash_SHA2_update_last_224(
        s: *mut u32,
        prev_len: u64,
        input: *mut u8,
        input_len: u32,
    );
}
extern "C" {
    pub fn Hacl_Hash_SHA2_update_last_256(
        s: *mut u32,
        prev_len: u64,
        input: *mut u8,
        input_len: u32,
    );
}
extern "C" {
    pub fn Hacl_Hash_SHA2_update_last_384(
        s: *mut u64,
        prev_len: FStar_UInt128_uint128,
        input: *mut u8,
        input_len: u32,
    );
}
extern "C" {
    pub fn Hacl_Hash_SHA2_update_last_512(
        s: *mut u64,
        prev_len: FStar_UInt128_uint128,
        input: *mut u8,
        input_len: u32,
    );
}
extern "C" {
    pub fn Hacl_Hash_SHA2_hash_224(input: *mut u8, input_len: u32, dst: *mut u8);
}
extern "C" {
    pub fn Hacl_Hash_SHA2_hash_256(input: *mut u8, input_len: u32, dst: *mut u8);
}
extern "C" {
    pub fn Hacl_Hash_SHA2_hash_384(input: *mut u8, input_len: u32, dst: *mut u8);
}
extern "C" {
    pub fn Hacl_Hash_SHA2_hash_512(input: *mut u8, input_len: u32, dst: *mut u8);
}
extern "C" {
    pub fn Hacl_Hash_Core_SHA2_init_224(s: *mut u32);
}
extern "C" {
    pub fn Hacl_Hash_Core_SHA2_init_256(s: *mut u32);
}
extern "C" {
    pub fn Hacl_Hash_Core_SHA2_init_384(s: *mut u64);
}
extern "C" {
    pub fn Hacl_Hash_Core_SHA2_init_512(s: *mut u64);
}
extern "C" {
    pub fn Hacl_Hash_Core_SHA2_update_224(hash: *mut u32, block: *mut u8);
}
extern "C" {
    pub fn Hacl_Hash_Core_SHA2_update_256(hash: *mut u32, block: *mut u8);
}
extern "C" {
    pub fn Hacl_Hash_Core_SHA2_update_384(hash: *mut u64, block: *mut u8);
}
extern "C" {
    pub fn Hacl_Hash_Core_SHA2_update_512(hash: *mut u64, block: *mut u8);
}
extern "C" {
    pub fn Hacl_Hash_Core_SHA2_pad_224(len: u64, dst: *mut u8);
}
extern "C" {
    pub fn Hacl_Hash_Core_SHA2_pad_256(len: u64, dst: *mut u8);
}
extern "C" {
    pub fn Hacl_Hash_Core_SHA2_pad_384(len: FStar_UInt128_uint128, dst: *mut u8);
}
extern "C" {
    pub fn Hacl_Hash_Core_SHA2_pad_512(len: FStar_UInt128_uint128, dst: *mut u8);
}
extern "C" {
    pub fn Hacl_Hash_Core_SHA2_finish_224(s: *mut u32, dst: *mut u8);
}
extern "C" {
    pub fn Hacl_Hash_Core_SHA2_finish_256(s: *mut u32, dst: *mut u8);
}
extern "C" {
    pub fn Hacl_Hash_Core_SHA2_finish_384(s: *mut u64, dst: *mut u8);
}
extern "C" {
    pub fn Hacl_Hash_Core_SHA2_finish_512(s: *mut u64, dst: *mut u8);
}
extern "C" {
    pub fn Hacl_Hash_Definitions_word_len(a: Spec_Hash_Definitions_hash_alg) -> u32;
}
extern "C" {
    pub fn Hacl_Hash_Definitions_block_len(a: Spec_Hash_Definitions_hash_alg) -> u32;
}
extern "C" {
    pub fn Hacl_Hash_Definitions_hash_word_len(a: Spec_Hash_Definitions_hash_alg) -> u32;
}
extern "C" {
    pub fn Hacl_Hash_Definitions_hash_len(a: Spec_Hash_Definitions_hash_alg) -> u32;
}
